// <auto-generated />
using System;
using BookShob.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShob.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BookShob.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("catName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("catOrder")
                        .HasColumnType("int");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("Id");

                    b.HasIndex("catName");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            catName = "Category 1",
                            catOrder = 1,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            catName = "Category 2",
                            catOrder = 2,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            catName = "Category 3",
                            catOrder = 3,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            catName = "Category 4",
                            catOrder = 4,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            catName = "Category 5",
                            catOrder = 5,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            catName = "Category 6",
                            catOrder = 6,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            catName = "Category 7",
                            catOrder = 7,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            catName = "Category 8",
                            catOrder = 8,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            catName = "Category 9",
                            catOrder = 9,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            catName = "Category 10",
                            catOrder = 10,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            catName = "Category 11",
                            catOrder = 11,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            catName = "Category 12",
                            catOrder = 12,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            catName = "Category 13",
                            catOrder = 13,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            catName = "Category 14",
                            catOrder = 14,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            catName = "Category 15",
                            catOrder = 15,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            catName = "Category 16",
                            catOrder = 16,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            catName = "Category 17",
                            catOrder = 17,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            catName = "Category 18",
                            catOrder = 18,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            catName = "Category 19",
                            catOrder = 19,
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            catName = "Category 20",
                            catOrder = 20,
                            markedAsDeleted = false
                        });
                });

            modelBuilder.Entity("BookShob.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("BookPrice");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("markedAsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Author 1",
                            CategoryId = 1,
                            Description = "This is the description of Book 1",
                            Price = 10.0m,
                            Title = "Book 1",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            Author = "Author 2",
                            CategoryId = 2,
                            Description = "This is the description of Book 2",
                            Price = 20.0m,
                            Title = "Book 2",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            Author = "Author 3",
                            CategoryId = 3,
                            Description = "This is the description of Book 3",
                            Price = 30.0m,
                            Title = "Book 3",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            Author = "Author 4",
                            CategoryId = 4,
                            Description = "This is the description of Book 4",
                            Price = 40.0m,
                            Title = "Book 4",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            Author = "Author 5",
                            CategoryId = 5,
                            Description = "This is the description of Book 5",
                            Price = 50.0m,
                            Title = "Book 5",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            Author = "Author 6",
                            CategoryId = 6,
                            Description = "This is the description of Book 6",
                            Price = 60.0m,
                            Title = "Book 6",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            Author = "Author 7",
                            CategoryId = 7,
                            Description = "This is the description of Book 7",
                            Price = 70.0m,
                            Title = "Book 7",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            Author = "Author 8",
                            CategoryId = 8,
                            Description = "This is the description of Book 8",
                            Price = 80.0m,
                            Title = "Book 8",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            Author = "Author 9",
                            CategoryId = 9,
                            Description = "This is the description of Book 9",
                            Price = 90.0m,
                            Title = "Book 9",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            Author = "Author 10",
                            CategoryId = 10,
                            Description = "This is the description of Book 10",
                            Price = 100.0m,
                            Title = "Book 10",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            Author = "Author 11",
                            CategoryId = 11,
                            Description = "This is the description of Book 11",
                            Price = 110.0m,
                            Title = "Book 11",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            Author = "Author 12",
                            CategoryId = 12,
                            Description = "This is the description of Book 12",
                            Price = 120.0m,
                            Title = "Book 12",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            Author = "Author 13",
                            CategoryId = 13,
                            Description = "This is the description of Book 13",
                            Price = 130.0m,
                            Title = "Book 13",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            Author = "Author 14",
                            CategoryId = 14,
                            Description = "This is the description of Book 14",
                            Price = 140.0m,
                            Title = "Book 14",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            Author = "Author 15",
                            CategoryId = 15,
                            Description = "This is the description of Book 15",
                            Price = 150.0m,
                            Title = "Book 15",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            Author = "Author 16",
                            CategoryId = 16,
                            Description = "This is the description of Book 16",
                            Price = 160.0m,
                            Title = "Book 16",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            Author = "Author 17",
                            CategoryId = 17,
                            Description = "This is the description of Book 17",
                            Price = 170.0m,
                            Title = "Book 17",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            Author = "Author 18",
                            CategoryId = 18,
                            Description = "This is the description of Book 18",
                            Price = 180.0m,
                            Title = "Book 18",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            Author = "Author 19",
                            CategoryId = 19,
                            Description = "This is the description of Book 19",
                            Price = 190.0m,
                            Title = "Book 19",
                            markedAsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            Author = "Author 20",
                            CategoryId = 20,
                            Description = "This is the description of Book 20",
                            Price = 200.0m,
                            Title = "Book 20",
                            markedAsDeleted = false
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BookShob.Domain.Entities.Product", b =>
                {
                    b.HasOne("BookShob.Domain.Entities.Category", "category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BookShob.Domain.Entities.Category", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
